// Snapshot of the original hand-written demo content, used only to populate
// the database the first time you run `npm run db:seed`. After seeding,
// all editing happens through /admin — this file is not imported anywhere
// else in the app.
import type { HolidayPackage, Destination } from '@/types';

export const seedPackages: HolidayPackage[] = [
  {
    slug: 'maldives-overwater-escape',
    title: 'Maldives Overwater Villa Escape',
    destination: 'Maldives', country: 'Maldives',
    image: 'https://picsum.photos/seed/maldives-villa/1200/900',
    duration: '7 nights', nights: 7, price: 1899, originalPrice: 2299,
    airline: 'Emirates', hotel: 'Velaa Private Island', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'luxury',
    highlights: ['Private overwater villa with plunge pool', 'Return seaplane transfers', 'Daily spa credit'],
  },
  {
    slug: 'dubai-city-luxury',
    title: 'Dubai Skyline & Desert Luxury',
    destination: 'Dubai', country: 'United Arab Emirates',
    image: 'https://picsum.photos/seed/dubai-hotel/1200/900',
    duration: '5 nights', nights: 5, price: 799, originalPrice: 999,
    airline: 'Emirates', hotel: 'Address Downtown', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Burj Khalifa views', 'Desert safari with BBQ dinner', 'Private airport transfers'],
  },
  {
    slug: 'bali-honeymoon-retreat',
    title: 'Bali Honeymoon Retreat',
    destination: 'Bali', country: 'Indonesia',
    image: 'https://picsum.photos/seed/bali-villa/1200/900',
    duration: '10 nights', nights: 10, price: 1449, originalPrice: 1699,
    airline: 'Singapore Airlines', hotel: 'Ubud Private Pool Villas', hotelStars: 5, board: 'Half Board', transfers: true,
    category: 'honeymoon',
    highlights: ['Private infinity pool villa', 'Couples spa ritual', 'Sunrise Mount Batur trek'],
  },
  {
    slug: 'antalya-family-sun',
    title: 'Antalya Family All-Inclusive',
    destination: 'Antalya', country: 'Turkey',
    image: 'https://picsum.photos/seed/antalya-resort/1200/900',
    duration: '7 nights', nights: 7, price: 599, originalPrice: 749,
    airline: 'Turkish Airlines', hotel: 'Rixos Premium Belek', hotelStars: 5, board: 'Ultra All-Inclusive', transfers: true,
    category: 'family',
    highlights: ['Kids club & waterpark', 'Ultra all-inclusive dining', 'Direct flights from London'],
  },
  {
    slug: 'paris-city-break',
    title: 'Paris Boutique City Break',
    destination: 'Paris', country: 'France',
    image: 'https://picsum.photos/seed/paris-hotel/1200/900',
    duration: '3 nights', nights: 3, price: 349, originalPrice: 429,
    airline: 'British Airways', hotel: 'Le Marais Boutique Hotel', hotelStars: 4, board: 'Room Only', transfers: false,
    category: 'city',
    highlights: ['Central Marais location', 'Seine river cruise included', 'Skip-the-line Louvre tickets'],
  },
  {
    slug: 'phuket-beach-bliss',
    title: 'Phuket Beach Bliss',
    destination: 'Phuket', country: 'Thailand',
    image: 'https://picsum.photos/seed/phuket-resort/1200/900',
    duration: '9 nights', nights: 9, price: 1199, originalPrice: 1449,
    airline: 'Qatar Airways', hotel: 'Amari Phuket', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'beach',
    highlights: ['Beachfront resort', 'Phi Phi Islands day trip', 'Free room upgrade on booking'],
  },
];

export const seedDestinations: Destination[] = [
  { slug: 'london', city: 'London', country: 'United Kingdom', region: 'uk', image: 'https://picsum.photos/seed/london-skyline/1200/1400', fromPrice: 49, blurb: 'Royal history meets modern glamour on the Thames.' },
  { slug: 'manchester', city: 'Manchester', country: 'United Kingdom', region: 'uk', image: 'https://picsum.photos/seed/manchester-city/1200/1400', fromPrice: 39, blurb: 'Northern energy, world-class culture and sport.' },
  { slug: 'birmingham', city: 'Birmingham', country: 'United Kingdom', region: 'uk', image: 'https://picsum.photos/seed/birmingham-city/1200/1400', fromPrice: 35, blurb: 'The beating heart of the Midlands, reimagined.' },
  { slug: 'dubai', city: 'Dubai', country: 'United Arab Emirates', region: 'middleeast', image: 'https://picsum.photos/seed/dubai-skyline/1200/1400', fromPrice: 349, blurb: 'Soaring towers, golden deserts and five-star everything.' },
  { slug: 'new-york', city: 'New York', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/newyork-city/1200/1400', fromPrice: 429, blurb: 'The city that never sleeps, always dazzles.' },
  { slug: 'toronto', city: 'Toronto', country: 'Canada', region: 'americas', image: 'https://picsum.photos/seed/toronto-city/1200/1400', fromPrice: 459, blurb: 'Cosmopolitan charm on the shores of Lake Ontario.' },
  { slug: 'bangkok', city: 'Bangkok', country: 'Thailand', region: 'asia', image: 'https://picsum.photos/seed/bangkok-temple/1200/1400', fromPrice: 499, blurb: 'Ornate temples and electric street life collide.' },
  { slug: 'istanbul', city: 'Istanbul', country: 'Turkey', region: 'europe', image: 'https://picsum.photos/seed/istanbul-mosque/1200/1400', fromPrice: 189, blurb: 'Where East meets West across the Bosphorus.' },
  { slug: 'lahore', city: 'Lahore', country: 'Pakistan', region: 'asia', image: 'https://picsum.photos/seed/lahore-fort/1200/1400', fromPrice: 419, blurb: 'Mughal grandeur and legendary hospitality.' },
  { slug: 'islamabad', city: 'Islamabad', country: 'Pakistan', region: 'asia', image: 'https://picsum.photos/seed/islamabad-hills/1200/1400', fromPrice: 419, blurb: 'A capital framed by the Margalla Hills.' },
  { slug: 'karachi', city: 'Karachi', country: 'Pakistan', region: 'asia', image: 'https://picsum.photos/seed/karachi-coast/1200/1400', fromPrice: 399, blurb: 'Coastal energy on the Arabian Sea.' },
  { slug: 'paris', city: 'Paris', country: 'France', region: 'europe', image: 'https://picsum.photos/seed/paris-eiffel/1200/1400', fromPrice: 79, blurb: 'Timeless elegance along the Seine.' },
  { slug: 'rome', city: 'Rome', country: 'Italy', region: 'europe', image: 'https://picsum.photos/seed/rome-colosseum/1200/1400', fromPrice: 89, blurb: 'Three thousand years of history, one unforgettable table.' },
  { slug: 'maldives', city: 'Maldives', country: 'Maldives', region: 'asia', image: 'https://picsum.photos/seed/maldives-overwater/1200/1400', fromPrice: 899, blurb: 'Overwater villas above impossibly turquoise water.' },
  { slug: 'bali', city: 'Bali', country: 'Indonesia', region: 'asia', image: 'https://picsum.photos/seed/bali-rice/1200/1400', fromPrice: 749, blurb: 'Emerald rice terraces and soulful serenity.' },
  { slug: 'phuket', city: 'Phuket', country: 'Thailand', region: 'asia', image: 'https://picsum.photos/seed/phuket-beach/1200/1400', fromPrice: 619, blurb: 'Andaman Sea beaches with a resort for every mood.' },
  { slug: 'antalya', city: 'Antalya', country: 'Turkey', region: 'europe', image: 'https://picsum.photos/seed/antalya-coast/1200/1400', fromPrice: 159, blurb: 'Turquoise Coast luxury without the long-haul price tag.' },
  { slug: 'vancouver', city: 'Vancouver', country: 'Canada', region: 'americas', image: 'https://picsum.photos/seed/vancouver-mountains/1200/1400', fromPrice: 479, blurb: 'Mountains meet ocean on Canada’s west coast.' },
  { slug: 'orlando', city: 'Orlando', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/orlando-parks/1200/1400', fromPrice: 449, blurb: 'Theme park magic for every member of the family.' },
  { slug: 'sydney', city: 'Sydney', country: 'Australia', region: 'oceania', image: 'https://picsum.photos/seed/sydney-harbour/1200/1400', fromPrice: 799, blurb: 'Harbour views, golden beaches, endless sunshine.' },
];
