// Snapshot of the original hand-written demo content, used only to populate
// the database the first time you run `npm run db:seed`. After seeding,
// all editing happens through /admin — this file is not imported anywhere
// else in the app.
import type { HolidayPackage, Destination } from '@/types';

export const seedPackages: HolidayPackage[] = [
  {
    slug: 'maldives-overwater-escape',
    title: 'Maldives Overwater Villa Escape',
    destination: 'Maldives', country: 'Maldives',
    image: 'https://picsum.photos/seed/maldives-villa/1200/900',
    duration: '7 nights', nights: 7, price: 1899, originalPrice: 2299,
    airline: 'Emirates', hotel: 'Velaa Private Island', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'luxury',
    highlights: ['Private overwater villa with plunge pool', 'Return seaplane transfers', 'Daily spa credit'],
  },
  {
    slug: 'dubai-city-luxury',
    title: 'Dubai Skyline & Desert Luxury',
    destination: 'Dubai', country: 'United Arab Emirates',
    image: 'https://picsum.photos/seed/dubai-hotel/1200/900',
    duration: '5 nights', nights: 5, price: 799, originalPrice: 999,
    airline: 'Emirates', hotel: 'Address Downtown', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Burj Khalifa views', 'Desert safari with BBQ dinner', 'Private airport transfers'],
  },
  {
    slug: 'bali-honeymoon-retreat',
    title: 'Bali Honeymoon Retreat',
    destination: 'Bali', country: 'Indonesia',
    image: 'https://picsum.photos/seed/bali-villa/1200/900',
    duration: '10 nights', nights: 10, price: 1449, originalPrice: 1699,
    airline: 'Singapore Airlines', hotel: 'Ubud Private Pool Villas', hotelStars: 5, board: 'Half Board', transfers: true,
    category: 'honeymoon',
    highlights: ['Private infinity pool villa', 'Couples spa ritual', 'Sunrise Mount Batur trek'],
  },
  {
    slug: 'antalya-family-sun',
    title: 'Antalya Family All-Inclusive',
    destination: 'Antalya', country: 'Turkey',
    image: 'https://picsum.photos/seed/antalya-resort/1200/900',
    duration: '7 nights', nights: 7, price: 599, originalPrice: 749,
    airline: 'Turkish Airlines', hotel: 'Rixos Premium Belek', hotelStars: 5, board: 'Ultra All-Inclusive', transfers: true,
    category: 'family',
    highlights: ['Kids club & waterpark', 'Ultra all-inclusive dining', 'Direct flights from London'],
  },
  {
    slug: 'paris-city-break',
    title: 'Paris Boutique City Break',
    destination: 'Paris', country: 'France',
    image: 'https://picsum.photos/seed/paris-hotel/1200/900',
    duration: '3 nights', nights: 3, price: 349, originalPrice: 429,
    airline: 'British Airways', hotel: 'Le Marais Boutique Hotel', hotelStars: 4, board: 'Room Only', transfers: false,
    category: 'city',
    highlights: ['Central Marais location', 'Seine river cruise included', 'Skip-the-line Louvre tickets'],
  },
  {
    slug: 'phuket-beach-bliss',
    title: 'Phuket Beach Bliss',
    destination: 'Phuket', country: 'Thailand',
    image: 'https://picsum.photos/seed/phuket-resort/1200/900',
    duration: '9 nights', nights: 9, price: 1199, originalPrice: 1449,
    airline: 'Qatar Airways', hotel: 'Amari Phuket', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'beach',
    highlights: ['Beachfront resort', 'Phi Phi Islands day trip', 'Free room upgrade on booking'],
  },
  {
    slug: 'barcelona-boutique-break',
    title: 'Barcelona Boutique City Break',
    destination: 'Barcelona', country: 'Spain',
    image: 'https://picsum.photos/seed/barcelona-hotel/1200/900',
    duration: '4 nights', nights: 4, price: 389, originalPrice: 459,
    airline: 'Vueling', hotel: 'Casa Gracia Barcelona', hotelStars: 4, board: 'Bed & Breakfast', transfers: false,
    category: 'city',
    highlights: ['Gothic Quarter walking tour', 'Sagrada Família skip-the-line tickets', 'Boutique hotel in Eixample'],
  },
  {
    slug: 'santorini-honeymoon-cliffside',
    title: 'Santorini Honeymoon Cliffside Suites',
    destination: 'Santorini', country: 'Greece',
    image: 'https://picsum.photos/seed/santorini-suite/1200/900',
    duration: '6 nights', nights: 6, price: 1699, originalPrice: 1999,
    airline: 'Aegean Airlines', hotel: 'Canaves Oia Suites', hotelStars: 5, board: 'Half Board', transfers: true,
    category: 'honeymoon',
    highlights: ['Caldera-view infinity pool suite', 'Private sunset catamaran cruise', 'Couples wine-tasting experience'],
  },
  {
    slug: 'lisbon-porto-discovery',
    title: 'Lisbon & Porto Discovery',
    destination: 'Lisbon', country: 'Portugal',
    image: 'https://picsum.photos/seed/lisbon-hotel/1200/900',
    duration: '6 nights', nights: 6, price: 599, originalPrice: 699,
    airline: 'TAP Portugal', hotel: 'Torel Avantgarde', hotelStars: 4, board: 'Bed & Breakfast', transfers: false,
    category: 'city',
    highlights: ['Two iconic Portuguese cities', 'Douro Valley wine-tasting day trip', 'Historic tram tours included'],
  },
  {
    slug: 'costa-del-sol-family-sun',
    title: 'Costa del Sol Family Sunshine',
    destination: 'Malaga', country: 'Spain',
    image: 'https://picsum.photos/seed/malaga-resort/1200/900',
    duration: '7 nights', nights: 7, price: 749, originalPrice: 899,
    airline: 'easyJet', hotel: 'Hotel Guadalpin Banús', hotelStars: 4, board: 'All-Inclusive', transfers: true,
    category: 'family',
    highlights: ['Kids club & water park access', 'Family rooms with sea views', 'Direct flights from major UK airports'],
  },
  {
    slug: 'abu-dhabi-desert-luxury',
    title: 'Abu Dhabi Desert & Luxury Skyline',
    destination: 'Abu Dhabi', country: 'United Arab Emirates',
    image: 'https://picsum.photos/seed/abudhabi-hotel/1200/900',
    duration: '5 nights', nights: 5, price: 1299, originalPrice: 1549,
    airline: 'Etihad Airways', hotel: 'Emirates Palace Mandarin Oriental', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'luxury',
    highlights: ['Sheikh Zayed Grand Mosque tour', 'Overnight desert safari glamping', 'Louvre Abu Dhabi private tour'],
  },
  {
    slug: 'singapore-marina-bay-city',
    title: 'Singapore Marina Bay City Escape',
    destination: 'Singapore', country: 'Singapore',
    image: 'https://picsum.photos/seed/singapore-hotel/1200/900',
    duration: '5 nights', nights: 5, price: 1099, originalPrice: 1299,
    airline: 'Singapore Airlines', hotel: 'Marina Bay Sands', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Infinity pool with skyline views', 'Gardens by the Bay night tour', 'Michelin-starred hawker food trail'],
  },
  {
    slug: 'tokyo-neon-explorer',
    title: 'Tokyo Neon Explorer',
    destination: 'Tokyo', country: 'Japan',
    image: 'https://picsum.photos/seed/tokyo-hotel/1200/900',
    duration: '6 nights', nights: 6, price: 1599, originalPrice: 1899,
    airline: 'ANA', hotel: 'Park Hyatt Tokyo', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Shibuya & Shinjuku night tour', 'Mount Fuji day trip', 'Traditional kaiseki dining experience'],
  },
  {
    slug: 'hurghada-red-sea-allinclusive',
    title: 'Hurghada Red Sea All-Inclusive',
    destination: 'Hurghada', country: 'Egypt',
    image: 'https://picsum.photos/seed/hurghada-resort/1200/900',
    duration: '7 nights', nights: 7, price: 649, originalPrice: 799,
    airline: 'EgyptAir', hotel: 'Steigenberger Al Dau Beach', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'beach',
    highlights: ['Private beach with coral reef snorkelling', 'Ultra all-inclusive dining', 'Red Sea sunset cruise included'],
  },
  {
    slug: 'marrakech-riad-retreat',
    title: 'Marrakech Riad Retreat',
    destination: 'Marrakech', country: 'Morocco',
    image: 'https://picsum.photos/seed/marrakech-riad/1200/900',
    duration: '4 nights', nights: 4, price: 429, originalPrice: 499,
    airline: 'Royal Air Maroc', hotel: 'La Sultana Marrakech', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Traditional riad with rooftop terrace', 'Atlas Mountains day excursion', 'Private hammam spa experience'],
  },
  {
    slug: 'cancun-caribbean-family',
    title: 'Cancun Caribbean Family Resort',
    destination: 'Cancun', country: 'Mexico',
    image: 'https://picsum.photos/seed/cancun-resort/1200/900',
    duration: '7 nights', nights: 7, price: 1199, originalPrice: 1399,
    airline: 'British Airways', hotel: 'Hyatt Ziva Cancun', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'family',
    highlights: ['Kids club and family pools', 'Ultra all-inclusive dining & drinks', 'White-sand Caribbean beachfront'],
  },
  {
    slug: 'rio-copacabana-city-break',
    title: 'Rio Copacabana City Break',
    destination: 'Rio de Janeiro', country: 'Brazil',
    image: 'https://picsum.photos/seed/rio-hotel/1200/900',
    duration: '6 nights', nights: 6, price: 1099, originalPrice: 1299,
    airline: 'TAP Portugal', hotel: 'Copacabana Palace', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Christ the Redeemer & Sugarloaf tours', 'Copacabana beachfront hotel', 'Samba show experience included'],
  },
  {
    slug: 'sydney-harbour-highlights',
    title: 'Sydney Harbour Highlights',
    destination: 'Sydney', country: 'Australia',
    image: 'https://picsum.photos/seed/sydney-hotel/1200/900',
    duration: '8 nights', nights: 8, price: 1799, originalPrice: 2099,
    airline: 'Qantas', hotel: 'Park Hyatt Sydney', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'luxury',
    highlights: ['Opera House harbour views', 'Blue Mountains day trip', 'Bondi Beach coastal walk'],
  },
  {
    slug: 'fiji-overwater-honeymoon',
    title: 'Fiji Overwater Honeymoon Bliss',
    destination: 'Fiji', country: 'Fiji',
    image: 'https://picsum.photos/seed/fiji-bure/1200/900',
    duration: '7 nights', nights: 7, price: 2399, originalPrice: 2799,
    airline: 'Fiji Airways', hotel: 'Likuliku Lagoon Resort', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'honeymoon',
    highlights: ['Overwater bure with lagoon access', 'Private sandbank picnic', 'Adults-only tranquil setting'],
  },
  {
    slug: 'amsterdam-canal-city-break',
    title: 'Amsterdam Canal City Break',
    destination: 'Amsterdam', country: 'Netherlands',
    image: 'https://picsum.photos/seed/amsterdam-hotel/1200/900',
    duration: '3 nights', nights: 3, price: 319, originalPrice: 379,
    airline: 'KLM', hotel: 'Pulitzer Amsterdam', hotelStars: 4, board: 'Bed & Breakfast', transfers: false,
    category: 'city',
    highlights: ['Canal-side boutique hotel', 'Van Gogh Museum skip-the-line tickets', 'Evening canal cruise included'],
  },
  {
    slug: 'prague-fairytale-getaway',
    title: 'Prague Fairytale Getaway',
    destination: 'Prague', country: 'Czech Republic',
    image: 'https://picsum.photos/seed/prague-hotel/1200/900',
    duration: '4 nights', nights: 4, price: 369, originalPrice: 429,
    airline: 'Czech Airlines', hotel: 'Aria Hotel Prague', hotelStars: 4, board: 'Bed & Breakfast', transfers: false,
    category: 'city',
    highlights: ['Old Town Square walking tour', 'Prague Castle guided visit', 'Boutique hotel in Malá Strana'],
  },
  {
    slug: 'mauritius-luxury-beach-escape',
    title: 'Mauritius Luxury Beach Escape',
    destination: 'Mauritius', country: 'Mauritius',
    image: 'https://picsum.photos/seed/mauritius-resort/1200/900',
    duration: '8 nights', nights: 8, price: 2199, originalPrice: 2599,
    airline: 'Air Mauritius', hotel: 'One&Only Le Saint Géran', hotelStars: 5, board: 'Half Board', transfers: true,
    category: 'luxury',
    highlights: ['Private beach villa options', 'Indian Ocean water sports included', 'Award-winning spa experience'],
  },
  {
    slug: 'seychelles-honeymoon-paradise',
    title: 'Seychelles Honeymoon Paradise',
    destination: 'Seychelles', country: 'Seychelles',
    image: 'https://picsum.photos/seed/seychelles-villa/1200/900',
    duration: '7 nights', nights: 7, price: 2599, originalPrice: 2999,
    airline: 'Emirates', hotel: 'Four Seasons Resort Seychelles', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'honeymoon',
    highlights: ['Hillside villa with private pool', 'Secluded beach coves', 'Sunset champagne cruise included'],
  },
  {
    slug: 'vietnam-halong-bay-luxury',
    title: 'Vietnam & Halong Bay Luxury Cruise',
    destination: 'Hanoi', country: 'Vietnam',
    image: 'https://picsum.photos/seed/halongbay-cruise/1200/900',
    duration: '8 nights', nights: 8, price: 1699, originalPrice: 1999,
    airline: 'Vietnam Airlines', hotel: 'La Siesta Hanoi + Halong Bay Cruise', hotelStars: 5, board: 'Half Board', transfers: true,
    category: 'luxury',
    highlights: ['Overnight luxury junk boat cruise', 'Hanoi Old Quarter exploration', 'Dramatic limestone karst scenery'],
  },
  {
    slug: 'jamaica-family-beach-resort',
    title: 'Jamaica Family Beach Resort',
    destination: 'Negril', country: 'Jamaica',
    image: 'https://picsum.photos/seed/jamaica-resort/1200/900',
    duration: '7 nights', nights: 7, price: 1399, originalPrice: 1649,
    airline: 'Virgin Atlantic', hotel: 'Beaches Negril Resort', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'family',
    highlights: ['Kids camp and water park', 'Ultra all-inclusive dining & entertainment', 'Seven-mile white sand beach'],
  },
  {
    slug: 'cape-town-luxury-getaway',
    title: 'Cape Town Luxury Getaway',
    destination: 'Cape Town', country: 'South Africa',
    image: 'https://picsum.photos/seed/capetown-hotel/1200/900',
    duration: '7 nights', nights: 7, price: 1599, originalPrice: 1899,
    airline: 'British Airways', hotel: 'One&Only Cape Town', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'luxury',
    highlights: ['Table Mountain private tour', 'Cape Winelands day excursion', 'Marina-front luxury suite'],
  },
];

export const seedDestinations: Destination[] = [
  { slug: 'tenerife', city: 'Tenerife', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/tenerife-coast/1200/1400', fromPrice: 69, blurb: 'Year-round Canary Islands sun, just a few hours away.' },
  { slug: 'sharm-el-sheikh', city: 'Sharm El Sheikh', country: 'Egypt', region: 'middleeast', image: 'https://picsum.photos/seed/sharm-elsheikh/1200/1400', fromPrice: 249, blurb: 'Red Sea diving and desert luxury on the Sinai coast.' },
  { slug: 'alicante', city: 'Alicante', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/alicante-coast/1200/1400', fromPrice: 49, blurb: 'The Costa Blanca’s classic sun-and-sea getaway.' },
  { slug: 'dubai', city: 'Dubai', country: 'United Arab Emirates', region: 'middleeast', image: 'https://picsum.photos/seed/dubai-skyline/1200/1400', fromPrice: 349, blurb: 'Soaring towers, golden deserts and five-star everything.' },
  { slug: 'new-york', city: 'New York', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/newyork-city/1200/1400', fromPrice: 429, blurb: 'The city that never sleeps, always dazzles.' },
  { slug: 'toronto', city: 'Toronto', country: 'Canada', region: 'americas', image: 'https://picsum.photos/seed/toronto-city/1200/1400', fromPrice: 459, blurb: 'Cosmopolitan charm on the shores of Lake Ontario.' },
  { slug: 'bangkok', city: 'Bangkok', country: 'Thailand', region: 'asia', image: 'https://picsum.photos/seed/bangkok-temple/1200/1400', fromPrice: 499, blurb: 'Ornate temples and electric street life collide.' },
  { slug: 'istanbul', city: 'Istanbul', country: 'Turkey', region: 'europe', image: 'https://picsum.photos/seed/istanbul-mosque/1200/1400', fromPrice: 189, blurb: 'Where East meets West across the Bosphorus.' },
  { slug: 'lahore', city: 'Lahore', country: 'Pakistan', region: 'asia', image: 'https://picsum.photos/seed/lahore-fort/1200/1400', fromPrice: 419, blurb: 'Mughal grandeur and legendary hospitality.' },
  { slug: 'islamabad', city: 'Islamabad', country: 'Pakistan', region: 'asia', image: 'https://picsum.photos/seed/islamabad-hills/1200/1400', fromPrice: 419, blurb: 'A capital framed by the Margalla Hills.' },
  { slug: 'karachi', city: 'Karachi', country: 'Pakistan', region: 'asia', image: 'https://picsum.photos/seed/karachi-coast/1200/1400', fromPrice: 399, blurb: 'Coastal energy on the Arabian Sea.' },
  { slug: 'paris', city: 'Paris', country: 'France', region: 'europe', image: 'https://picsum.photos/seed/paris-eiffel/1200/1400', fromPrice: 79, blurb: 'Timeless elegance along the Seine.' },
  { slug: 'rome', city: 'Rome', country: 'Italy', region: 'europe', image: 'https://picsum.photos/seed/rome-colosseum/1200/1400', fromPrice: 89, blurb: 'Three thousand years of history, one unforgettable table.' },
  { slug: 'maldives', city: 'Maldives', country: 'Maldives', region: 'asia', image: 'https://picsum.photos/seed/maldives-overwater/1200/1400', fromPrice: 899, blurb: 'Overwater villas above impossibly turquoise water.' },
  { slug: 'bali', city: 'Bali', country: 'Indonesia', region: 'asia', image: 'https://picsum.photos/seed/bali-rice/1200/1400', fromPrice: 749, blurb: 'Emerald rice terraces and soulful serenity.' },
  { slug: 'phuket', city: 'Phuket', country: 'Thailand', region: 'asia', image: 'https://picsum.photos/seed/phuket-beach/1200/1400', fromPrice: 619, blurb: 'Andaman Sea beaches with a resort for every mood.' },
  { slug: 'antalya', city: 'Antalya', country: 'Turkey', region: 'europe', image: 'https://picsum.photos/seed/antalya-coast/1200/1400', fromPrice: 159, blurb: 'Turquoise Coast luxury without the long-haul price tag.' },
  { slug: 'vancouver', city: 'Vancouver', country: 'Canada', region: 'americas', image: 'https://picsum.photos/seed/vancouver-mountains/1200/1400', fromPrice: 479, blurb: 'Mountains meet ocean on Canada’s west coast.' },
  { slug: 'orlando', city: 'Orlando', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/orlando-parks/1200/1400', fromPrice: 449, blurb: 'Theme park magic for every member of the family.' },
  { slug: 'sydney', city: 'Sydney', country: 'Australia', region: 'oceania', image: 'https://picsum.photos/seed/sydney-harbour/1200/1400', fromPrice: 799, blurb: 'Harbour views, golden beaches, endless sunshine.' },

  { slug: 'faro', city: 'Faro', country: 'Portugal', region: 'europe', image: 'https://picsum.photos/seed/faro-algarve/1200/1400', fromPrice: 55, blurb: 'The Algarve’s golden cliffs and beach towns.' },
  { slug: 'gran-canaria', city: 'Gran Canaria', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/grancanaria-dunes/1200/1400', fromPrice: 75, blurb: 'Dunes, mountains and beaches on one Canary Island.' },

  // --- Europe ---
  { slug: 'barcelona', city: 'Barcelona', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/barcelona-city/1200/1400', fromPrice: 59, blurb: 'Gaudí’s masterpieces meet Mediterranean beach life.' },
  { slug: 'madrid', city: 'Madrid', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/madrid-city/1200/1400', fromPrice: 65, blurb: 'Grand boulevards, world-class art and tapas culture.' },
  { slug: 'amsterdam', city: 'Amsterdam', country: 'Netherlands', region: 'europe', image: 'https://picsum.photos/seed/amsterdam-canals/1200/1400', fromPrice: 45, blurb: 'Canal-side charm and effortless cool.' },
  { slug: 'berlin', city: 'Berlin', country: 'Germany', region: 'europe', image: 'https://picsum.photos/seed/berlin-city/1200/1400', fromPrice: 55, blurb: 'History, art and nightlife in equal, electric measure.' },
  { slug: 'munich', city: 'Munich', country: 'Germany', region: 'europe', image: 'https://picsum.photos/seed/munich-city/1200/1400', fromPrice: 69, blurb: 'Bavarian charm with Alpine views on the doorstep.' },
  { slug: 'frankfurt', city: 'Frankfurt', country: 'Germany', region: 'europe', image: 'https://picsum.photos/seed/frankfurt-skyline/1200/1400', fromPrice: 59, blurb: 'A skyline of glass towers on the river Main.' },
  { slug: 'vienna', city: 'Vienna', country: 'Austria', region: 'europe', image: 'https://picsum.photos/seed/vienna-city/1200/1400', fromPrice: 75, blurb: 'Imperial palaces, coffee houses and classical grandeur.' },
  { slug: 'prague', city: 'Prague', country: 'Czech Republic', region: 'europe', image: 'https://picsum.photos/seed/prague-city/1200/1400', fromPrice: 49, blurb: 'Fairytale spires above the Vltava River.' },
  { slug: 'budapest', city: 'Budapest', country: 'Hungary', region: 'europe', image: 'https://picsum.photos/seed/budapest-city/1200/1400', fromPrice: 45, blurb: 'Thermal baths and grand Danube-side architecture.' },
  { slug: 'lisbon', city: 'Lisbon', country: 'Portugal', region: 'europe', image: 'https://picsum.photos/seed/lisbon-city/1200/1400', fromPrice: 69, blurb: 'Pastel hills, trams and golden Atlantic light.' },
  { slug: 'porto', city: 'Porto', country: 'Portugal', region: 'europe', image: 'https://picsum.photos/seed/porto-city/1200/1400', fromPrice: 59, blurb: 'Port wine cellars along a riverside old town.' },
  { slug: 'milan', city: 'Milan', country: 'Italy', region: 'europe', image: 'https://picsum.photos/seed/milan-city/1200/1400', fromPrice: 55, blurb: 'Fashion, design and world-class dining.' },
  { slug: 'venice', city: 'Venice', country: 'Italy', region: 'europe', image: 'https://picsum.photos/seed/venice-canals/1200/1400', fromPrice: 65, blurb: 'Gondolas gliding through a city built on water.' },
  { slug: 'florence', city: 'Florence', country: 'Italy', region: 'europe', image: 'https://picsum.photos/seed/florence-city/1200/1400', fromPrice: 69, blurb: 'The cradle of the Renaissance, art at every turn.' },
  { slug: 'athens', city: 'Athens', country: 'Greece', region: 'europe', image: 'https://picsum.photos/seed/athens-acropolis/1200/1400', fromPrice: 89, blurb: 'Ancient wonders beneath the Acropolis.' },
  { slug: 'santorini', city: 'Santorini', country: 'Greece', region: 'europe', image: 'https://picsum.photos/seed/santorini-caldera/1200/1400', fromPrice: 129, blurb: 'Whitewashed cliffs above a volcanic caldera.' },
  { slug: 'mykonos', city: 'Mykonos', country: 'Greece', region: 'europe', image: 'https://picsum.photos/seed/mykonos-island/1200/1400', fromPrice: 135, blurb: 'Windmills, beach clubs and Cycladic charm.' },
  { slug: 'zurich', city: 'Zurich', country: 'Switzerland', region: 'europe', image: 'https://picsum.photos/seed/zurich-city/1200/1400', fromPrice: 89, blurb: 'Lakeside elegance at the foot of the Alps.' },
  { slug: 'geneva', city: 'Geneva', country: 'Switzerland', region: 'europe', image: 'https://picsum.photos/seed/geneva-lake/1200/1400', fromPrice: 85, blurb: 'A refined lakeside gateway to the Alps.' },
  { slug: 'brussels', city: 'Brussels', country: 'Belgium', region: 'europe', image: 'https://picsum.photos/seed/brussels-city/1200/1400', fromPrice: 39, blurb: 'Grand squares, chocolate and easy European charm.' },
  { slug: 'copenhagen', city: 'Copenhagen', country: 'Denmark', region: 'europe', image: 'https://picsum.photos/seed/copenhagen-city/1200/1400', fromPrice: 79, blurb: 'Scandinavian design and colourful harbourfronts.' },
  { slug: 'stockholm', city: 'Stockholm', country: 'Sweden', region: 'europe', image: 'https://picsum.photos/seed/stockholm-city/1200/1400', fromPrice: 89, blurb: 'A city built across fourteen island archipelagos.' },
  { slug: 'oslo', city: 'Oslo', country: 'Norway', region: 'europe', image: 'https://picsum.photos/seed/oslo-fjord/1200/1400', fromPrice: 95, blurb: 'Fjord views meet Scandinavian minimalism.' },
  { slug: 'reykjavik', city: 'Reykjavik', country: 'Iceland', region: 'europe', image: 'https://picsum.photos/seed/reykjavik-city/1200/1400', fromPrice: 149, blurb: 'Northern lights, hot springs and volcanic landscapes.' },
  { slug: 'dublin', city: 'Dublin', country: 'Ireland', region: 'europe', image: 'https://picsum.photos/seed/dublin-city/1200/1400', fromPrice: 35, blurb: 'Literary pubs and easy Irish hospitality.' },
  { slug: 'nice', city: 'Nice', country: 'France', region: 'europe', image: 'https://picsum.photos/seed/nice-riviera/1200/1400', fromPrice: 65, blurb: 'Riviera glamour on the Baie des Anges.' },
  { slug: 'malaga', city: 'Malaga', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/malaga-coast/1200/1400', fromPrice: 55, blurb: 'Gateway to the Costa del Sol’s golden beaches.' },
  { slug: 'palma-de-mallorca', city: 'Palma de Mallorca', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/palma-mallorca/1200/1400', fromPrice: 59, blurb: 'Balearic beaches with a historic old town.' },

  // --- Middle East & North Africa ---
  { slug: 'abu-dhabi', city: 'Abu Dhabi', country: 'United Arab Emirates', region: 'middleeast', image: 'https://picsum.photos/seed/abudhabi-skyline/1200/1400', fromPrice: 379, blurb: 'Grand mosques and desert luxury on the Gulf.' },
  { slug: 'doha', city: 'Doha', country: 'Qatar', region: 'middleeast', image: 'https://picsum.photos/seed/doha-skyline/1200/1400', fromPrice: 359, blurb: 'A futuristic skyline on the Arabian Gulf.' },
  { slug: 'muscat', city: 'Muscat', country: 'Oman', region: 'middleeast', image: 'https://picsum.photos/seed/muscat-city/1200/1400', fromPrice: 399, blurb: 'Whitewashed forts against dramatic desert mountains.' },
  { slug: 'riyadh', city: 'Riyadh', country: 'Saudi Arabia', region: 'middleeast', image: 'https://picsum.photos/seed/riyadh-skyline/1200/1400', fromPrice: 389, blurb: 'A capital transforming at extraordinary pace.' },
  { slug: 'jeddah', city: 'Jeddah', country: 'Saudi Arabia', region: 'middleeast', image: 'https://picsum.photos/seed/jeddah-corniche/1200/1400', fromPrice: 399, blurb: 'A historic Red Sea gateway with a modern corniche.' },
  { slug: 'manama', city: 'Manama', country: 'Bahrain', region: 'middleeast', image: 'https://picsum.photos/seed/manama-skyline/1200/1400', fromPrice: 369, blurb: 'A compact island capital rich in pearl-diving history.' },
  { slug: 'amman', city: 'Amman', country: 'Jordan', region: 'middleeast', image: 'https://picsum.photos/seed/amman-city/1200/1400', fromPrice: 329, blurb: 'Gateway to Petra and the ancient Levant.' },
  { slug: 'beirut', city: 'Beirut', country: 'Lebanon', region: 'middleeast', image: 'https://picsum.photos/seed/beirut-city/1200/1400', fromPrice: 349, blurb: 'Mediterranean energy layered with deep history.' },
  { slug: 'tel-aviv', city: 'Tel Aviv', country: 'Israel', region: 'middleeast', image: 'https://picsum.photos/seed/telaviv-beach/1200/1400', fromPrice: 299, blurb: 'Beach city energy on the eastern Mediterranean.' },
  { slug: 'cairo', city: 'Cairo', country: 'Egypt', region: 'middleeast', image: 'https://picsum.photos/seed/cairo-pyramids/1200/1400', fromPrice: 279, blurb: 'The pyramids of Giza on the edge of a mega-city.' },
  { slug: 'marrakech', city: 'Marrakech', country: 'Morocco', region: 'middleeast', image: 'https://picsum.photos/seed/marrakech-medina/1200/1400', fromPrice: 99, blurb: 'Souks, riads and the Atlas Mountains beyond.' },
  { slug: 'hurghada', city: 'Hurghada', country: 'Egypt', region: 'middleeast', image: 'https://picsum.photos/seed/hurghada-redsea/1200/1400', fromPrice: 219, blurb: 'Red Sea reefs and year-round desert sunshine.' },

  // --- Asia ---
  { slug: 'singapore', city: 'Singapore', country: 'Singapore', region: 'asia', image: 'https://picsum.photos/seed/singapore-skyline/1200/1400', fromPrice: 549, blurb: 'A gleaming garden city at the crossroads of Asia.' },
  { slug: 'kuala-lumpur', city: 'Kuala Lumpur', country: 'Malaysia', region: 'asia', image: 'https://picsum.photos/seed/kualalumpur-towers/1200/1400', fromPrice: 499, blurb: 'Twin towers rising over a melting-pot capital.' },
  { slug: 'hong-kong', city: 'Hong Kong', country: 'Hong Kong', region: 'asia', image: 'https://picsum.photos/seed/hongkong-skyline/1200/1400', fromPrice: 579, blurb: 'A dazzling harbour skyline like nowhere else.' },
  { slug: 'tokyo', city: 'Tokyo', country: 'Japan', region: 'asia', image: 'https://picsum.photos/seed/tokyo-shibuya/1200/1400', fromPrice: 649, blurb: 'Neon streets, ancient shrines and precision in everything.' },
  { slug: 'osaka', city: 'Osaka', country: 'Japan', region: 'asia', image: 'https://picsum.photos/seed/osaka-castle/1200/1400', fromPrice: 679, blurb: 'Japan’s food capital, warm and unpretentious.' },
  { slug: 'seoul', city: 'Seoul', country: 'South Korea', region: 'asia', image: 'https://picsum.photos/seed/seoul-city/1200/1400', fromPrice: 619, blurb: 'Ancient palaces beside a hyper-modern skyline.' },
  { slug: 'beijing', city: 'Beijing', country: 'China', region: 'asia', image: 'https://picsum.photos/seed/beijing-city/1200/1400', fromPrice: 549, blurb: 'The Great Wall and imperial history at the capital.' },
  { slug: 'shanghai', city: 'Shanghai', country: 'China', region: 'asia', image: 'https://picsum.photos/seed/shanghai-skyline/1200/1400', fromPrice: 569, blurb: 'A futuristic skyline above a historic riverside Bund.' },
  { slug: 'delhi', city: 'Delhi', country: 'India', region: 'asia', image: 'https://picsum.photos/seed/delhi-city/1200/1400', fromPrice: 449, blurb: 'Mughal monuments amid a vast, vibrant capital.' },
  { slug: 'mumbai', city: 'Mumbai', country: 'India', region: 'asia', image: 'https://picsum.photos/seed/mumbai-city/1200/1400', fromPrice: 469, blurb: 'India’s coastal city of dreams and colour.' },
  { slug: 'colombo', city: 'Colombo', country: 'Sri Lanka', region: 'asia', image: 'https://picsum.photos/seed/colombo-city/1200/1400', fromPrice: 529, blurb: 'A tropical gateway to tea country and ancient temples.' },
  { slug: 'ho-chi-minh-city', city: 'Ho Chi Minh City', country: 'Vietnam', region: 'asia', image: 'https://picsum.photos/seed/hochiminh-city/1200/1400', fromPrice: 559, blurb: 'Motorbike energy and street food on every corner.' },
  { slug: 'hanoi', city: 'Hanoi', country: 'Vietnam', region: 'asia', image: 'https://picsum.photos/seed/hanoi-city/1200/1400', fromPrice: 549, blurb: 'Old Quarter charm, gateway to Halong Bay.' },
  { slug: 'manila', city: 'Manila', country: 'Philippines', region: 'asia', image: 'https://picsum.photos/seed/manila-city/1200/1400', fromPrice: 599, blurb: 'A vibrant capital gateway to 7,000 islands.' },
  { slug: 'jakarta', city: 'Jakarta', country: 'Indonesia', region: 'asia', image: 'https://picsum.photos/seed/jakarta-city/1200/1400', fromPrice: 589, blurb: 'A sprawling capital at the heart of the archipelago.' },
  { slug: 'kathmandu', city: 'Kathmandu', country: 'Nepal', region: 'asia', image: 'https://picsum.photos/seed/kathmandu-city/1200/1400', fromPrice: 599, blurb: 'Himalayan peaks framing an ancient valley capital.' },

  // --- Americas ---
  { slug: 'los-angeles', city: 'Los Angeles', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/losangeles-city/1200/1400', fromPrice: 449, blurb: 'Sunshine, studios and the Pacific coastline.' },
  { slug: 'san-francisco', city: 'San Francisco', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/sanfrancisco-bay/1200/1400', fromPrice: 469, blurb: 'Fog-kissed hills above the Golden Gate.' },
  { slug: 'chicago', city: 'Chicago', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/chicago-skyline/1200/1400', fromPrice: 419, blurb: 'Bold architecture on the shores of Lake Michigan.' },
  { slug: 'miami', city: 'Miami', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/miami-beach/1200/1400', fromPrice: 399, blurb: 'Art deco glamour and endless beach energy.' },
  { slug: 'las-vegas', city: 'Las Vegas', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/lasvegas-strip/1200/1400', fromPrice: 459, blurb: 'Desert lights and non-stop entertainment on the Strip.' },
  { slug: 'boston', city: 'Boston', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/boston-city/1200/1400', fromPrice: 389, blurb: 'Colonial history along a walkable waterfront.' },
  { slug: 'washington-dc', city: 'Washington DC', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/washingtondc-monuments/1200/1400', fromPrice: 409, blurb: 'Monuments, museums and the seat of a nation.' },
  { slug: 'cancun', city: 'Cancun', country: 'Mexico', region: 'americas', image: 'https://picsum.photos/seed/cancun-beach/1200/1400', fromPrice: 549, blurb: 'Caribbean turquoise waters and Mayan ruins nearby.' },
  { slug: 'mexico-city', city: 'Mexico City', country: 'Mexico', region: 'americas', image: 'https://picsum.photos/seed/mexicocity-city/1200/1400', fromPrice: 499, blurb: 'Aztec history beneath a vast, colourful capital.' },
  { slug: 'rio-de-janeiro', city: 'Rio de Janeiro', country: 'Brazil', region: 'americas', image: 'https://picsum.photos/seed/rio-copacabana/1200/1400', fromPrice: 599, blurb: 'Christ the Redeemer watching over golden beaches.' },
  { slug: 'buenos-aires', city: 'Buenos Aires', country: 'Argentina', region: 'americas', image: 'https://picsum.photos/seed/buenosaires-city/1200/1400', fromPrice: 649, blurb: 'Tango, steakhouses and grand European boulevards.' },
  { slug: 'lima', city: 'Lima', country: 'Peru', region: 'americas', image: 'https://picsum.photos/seed/lima-city/1200/1400', fromPrice: 599, blurb: 'A coastal capital gateway to Machu Picchu.' },
  { slug: 'kingston-jamaica', city: 'Kingston', country: 'Jamaica', region: 'americas', image: 'https://picsum.photos/seed/kingston-jamaica/1200/1400', fromPrice: 579, blurb: 'Reggae roots and lush Caribbean mountains.' },
  { slug: 'nassau-bahamas', city: 'Nassau', country: 'Bahamas', region: 'americas', image: 'https://picsum.photos/seed/nassau-bahamas/1200/1400', fromPrice: 599, blurb: 'Powder-white sands across turquoise shallows.' },
  { slug: 'bridgetown-barbados', city: 'Bridgetown', country: 'Barbados', region: 'americas', image: 'https://picsum.photos/seed/bridgetown-barbados/1200/1400', fromPrice: 549, blurb: 'Rum, reggae and the friendliest shores in the Caribbean.' },
  { slug: 'montreal', city: 'Montreal', country: 'Canada', region: 'americas', image: 'https://picsum.photos/seed/montreal-city/1200/1400', fromPrice: 429, blurb: 'French joie de vivre on the St. Lawrence River.' },

  // --- Oceania ---
  { slug: 'auckland', city: 'Auckland', country: 'New Zealand', region: 'oceania', image: 'https://picsum.photos/seed/auckland-harbour/1200/1400', fromPrice: 949, blurb: 'A city of sails between two shimmering harbours.' },
  { slug: 'melbourne', city: 'Melbourne', country: 'Australia', region: 'oceania', image: 'https://picsum.photos/seed/melbourne-city/1200/1400', fromPrice: 799, blurb: 'Laneway culture, coffee and world-class sport.' },
  { slug: 'brisbane', city: 'Brisbane', country: 'Australia', region: 'oceania', image: 'https://picsum.photos/seed/brisbane-river/1200/1400', fromPrice: 819, blurb: 'Riverside sunshine, gateway to the Gold Coast.' },
  { slug: 'perth', city: 'Perth', country: 'Australia', region: 'oceania', image: 'https://picsum.photos/seed/perth-city/1200/1400', fromPrice: 749, blurb: 'Wide skies and pristine beaches on the west coast.' },
  { slug: 'nadi-fiji', city: 'Nadi', country: 'Fiji', region: 'oceania', image: 'https://picsum.photos/seed/nadi-fiji/1200/1400', fromPrice: 899, blurb: 'The gateway to Fiji’s scattered island paradise.' },
];
