// Snapshot of the original hand-written demo content, used only to populate
// the database the first time you run `npm run db:seed`. After seeding,
// all editing happens through /admin — this file is not imported anywhere
// else in the app.
import type { HolidayPackage, Destination } from '@/types';

export const seedPackages: HolidayPackage[] = [
  {
    slug: 'maldives-overwater-escape',
    title: 'Maldives Overwater Villa Escape',
    destination: 'Maldives', country: 'Maldives',
    image: 'https://picsum.photos/seed/maldives-villa/1200/900',
    duration: '7 nights', nights: 7, price: 1899, originalPrice: 2299,
    airline: 'Emirates', hotel: 'Velaa Private Island', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'luxury',
    highlights: ['Private overwater villa with plunge pool', 'Return seaplane transfers', 'Daily spa credit'],
  },
  {
    slug: 'dubai-city-luxury',
    title: 'Dubai Skyline & Desert Luxury',
    destination: 'Dubai', country: 'United Arab Emirates',
    image: 'https://picsum.photos/seed/dubai-hotel/1200/900',
    duration: '5 nights', nights: 5, price: 799, originalPrice: 999,
    airline: 'Emirates', hotel: 'Address Downtown', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Burj Khalifa views', 'Desert safari with BBQ dinner', 'Private airport transfers'],
  },
  {
    slug: 'bali-honeymoon-retreat',
    title: 'Bali Honeymoon Retreat',
    destination: 'Bali', country: 'Indonesia',
    image: 'https://picsum.photos/seed/bali-villa/1200/900',
    duration: '10 nights', nights: 10, price: 1449, originalPrice: 1699,
    airline: 'Singapore Airlines', hotel: 'Ubud Private Pool Villas', hotelStars: 5, board: 'Half Board', transfers: true,
    category: 'honeymoon',
    highlights: ['Private infinity pool villa', 'Couples spa ritual', 'Sunrise Mount Batur trek'],
  },
  {
    slug: 'antalya-family-sun',
    title: 'Antalya Family All-Inclusive',
    destination: 'Antalya', country: 'Turkey',
    image: 'https://picsum.photos/seed/antalya-resort/1200/900',
    duration: '7 nights', nights: 7, price: 599, originalPrice: 749,
    airline: 'Turkish Airlines', hotel: 'Rixos Premium Belek', hotelStars: 5, board: 'Ultra All-Inclusive', transfers: true,
    category: 'family',
    highlights: ['Kids club & waterpark', 'Ultra all-inclusive dining', 'Direct flights from London'],
  },
  {
    slug: 'paris-city-break',
    title: 'Paris Boutique City Break',
    destination: 'Paris', country: 'France',
    image: 'https://picsum.photos/seed/paris-hotel/1200/900',
    duration: '3 nights', nights: 3, price: 349, originalPrice: 429,
    airline: 'British Airways', hotel: 'Le Marais Boutique Hotel', hotelStars: 4, board: 'Room Only', transfers: false,
    category: 'city',
    highlights: ['Central Marais location', 'Seine river cruise included', 'Skip-the-line Louvre tickets'],
  },
  {
    slug: 'phuket-beach-bliss',
    title: 'Phuket Beach Bliss',
    destination: 'Phuket', country: 'Thailand',
    image: 'https://picsum.photos/seed/phuket-resort/1200/900',
    duration: '9 nights', nights: 9, price: 1199, originalPrice: 1449,
    airline: 'Qatar Airways', hotel: 'Amari Phuket', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'beach',
    highlights: ['Beachfront resort', 'Phi Phi Islands day trip', 'Free room upgrade on booking'],
  },
  {
    slug: 'barcelona-boutique-break',
    title: 'Barcelona Boutique City Break',
    destination: 'Barcelona', country: 'Spain',
    image: 'https://picsum.photos/seed/barcelona-hotel/1200/900',
    duration: '4 nights', nights: 4, price: 389, originalPrice: 459,
    airline: 'Vueling', hotel: 'Casa Gracia Barcelona', hotelStars: 4, board: 'Bed & Breakfast', transfers: false,
    category: 'city',
    highlights: ['Gothic Quarter walking tour', 'Sagrada Família skip-the-line tickets', 'Boutique hotel in Eixample'],
  },
  {
    slug: 'santorini-honeymoon-cliffside',
    title: 'Santorini Honeymoon Cliffside Suites',
    destination: 'Santorini', country: 'Greece',
    image: 'https://picsum.photos/seed/santorini-suite/1200/900',
    duration: '6 nights', nights: 6, price: 1699, originalPrice: 1999,
    airline: 'Aegean Airlines', hotel: 'Canaves Oia Suites', hotelStars: 5, board: 'Half Board', transfers: true,
    category: 'honeymoon',
    highlights: ['Caldera-view infinity pool suite', 'Private sunset catamaran cruise', 'Couples wine-tasting experience'],
  },
  {
    slug: 'lisbon-porto-discovery',
    title: 'Lisbon & Porto Discovery',
    destination: 'Lisbon', country: 'Portugal',
    image: 'https://picsum.photos/seed/lisbon-hotel/1200/900',
    duration: '6 nights', nights: 6, price: 599, originalPrice: 699,
    airline: 'TAP Portugal', hotel: 'Torel Avantgarde', hotelStars: 4, board: 'Bed & Breakfast', transfers: false,
    category: 'city',
    highlights: ['Two iconic Portuguese cities', 'Douro Valley wine-tasting day trip', 'Historic tram tours included'],
  },
  {
    slug: 'costa-del-sol-family-sun',
    title: 'Costa del Sol Family Sunshine',
    destination: 'Malaga', country: 'Spain',
    image: 'https://picsum.photos/seed/malaga-resort/1200/900',
    duration: '7 nights', nights: 7, price: 749, originalPrice: 899,
    airline: 'easyJet', hotel: 'Hotel Guadalpin Banús', hotelStars: 4, board: 'All-Inclusive', transfers: true,
    category: 'family',
    highlights: ['Kids club & water park access', 'Family rooms with sea views', 'Direct flights from major UK airports'],
  },
  {
    slug: 'abu-dhabi-desert-luxury',
    title: 'Abu Dhabi Desert & Luxury Skyline',
    destination: 'Abu Dhabi', country: 'United Arab Emirates',
    image: 'https://picsum.photos/seed/abudhabi-hotel/1200/900',
    duration: '5 nights', nights: 5, price: 1299, originalPrice: 1549,
    airline: 'Etihad Airways', hotel: 'Emirates Palace Mandarin Oriental', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'luxury',
    highlights: ['Sheikh Zayed Grand Mosque tour', 'Overnight desert safari glamping', 'Louvre Abu Dhabi private tour'],
  },
  {
    slug: 'singapore-marina-bay-city',
    title: 'Singapore Marina Bay City Escape',
    destination: 'Singapore', country: 'Singapore',
    image: 'https://picsum.photos/seed/singapore-hotel/1200/900',
    duration: '5 nights', nights: 5, price: 1099, originalPrice: 1299,
    airline: 'Singapore Airlines', hotel: 'Marina Bay Sands', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Infinity pool with skyline views', 'Gardens by the Bay night tour', 'Michelin-starred hawker food trail'],
  },
  {
    slug: 'tokyo-neon-explorer',
    title: 'Tokyo Neon Explorer',
    destination: 'Tokyo', country: 'Japan',
    image: 'https://picsum.photos/seed/tokyo-hotel/1200/900',
    duration: '6 nights', nights: 6, price: 1599, originalPrice: 1899,
    airline: 'ANA', hotel: 'Park Hyatt Tokyo', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Shibuya & Shinjuku night tour', 'Mount Fuji day trip', 'Traditional kaiseki dining experience'],
  },
  {
    slug: 'hurghada-red-sea-allinclusive',
    title: 'Hurghada Red Sea All-Inclusive',
    destination: 'Hurghada', country: 'Egypt',
    image: 'https://picsum.photos/seed/hurghada-resort/1200/900',
    duration: '7 nights', nights: 7, price: 649, originalPrice: 799,
    airline: 'EgyptAir', hotel: 'Steigenberger Al Dau Beach', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'beach',
    highlights: ['Private beach with coral reef snorkelling', 'Ultra all-inclusive dining', 'Red Sea sunset cruise included'],
  },
  {
    slug: 'marrakech-riad-retreat',
    title: 'Marrakech Riad Retreat',
    destination: 'Marrakech', country: 'Morocco',
    image: 'https://picsum.photos/seed/marrakech-riad/1200/900',
    duration: '4 nights', nights: 4, price: 429, originalPrice: 499,
    airline: 'Royal Air Maroc', hotel: 'La Sultana Marrakech', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Traditional riad with rooftop terrace', 'Atlas Mountains day excursion', 'Private hammam spa experience'],
  },
  {
    slug: 'cancun-caribbean-family',
    title: 'Cancun Caribbean Family Resort',
    destination: 'Cancun', country: 'Mexico',
    image: 'https://picsum.photos/seed/cancun-resort/1200/900',
    duration: '7 nights', nights: 7, price: 1199, originalPrice: 1399,
    airline: 'British Airways', hotel: 'Hyatt Ziva Cancun', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'family',
    highlights: ['Kids club and family pools', 'Ultra all-inclusive dining & drinks', 'White-sand Caribbean beachfront'],
  },
  {
    slug: 'rio-copacabana-city-break',
    title: 'Rio Copacabana City Break',
    destination: 'Rio de Janeiro', country: 'Brazil',
    image: 'https://picsum.photos/seed/rio-hotel/1200/900',
    duration: '6 nights', nights: 6, price: 1099, originalPrice: 1299,
    airline: 'TAP Portugal', hotel: 'Copacabana Palace', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'city',
    highlights: ['Christ the Redeemer & Sugarloaf tours', 'Copacabana beachfront hotel', 'Samba show experience included'],
  },
  {
    slug: 'sydney-harbour-highlights',
    title: 'Sydney Harbour Highlights',
    destination: 'Sydney', country: 'Australia',
    image: 'https://picsum.photos/seed/sydney-hotel/1200/900',
    duration: '8 nights', nights: 8, price: 1799, originalPrice: 2099,
    airline: 'Qantas', hotel: 'Park Hyatt Sydney', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'luxury',
    highlights: ['Opera House harbour views', 'Blue Mountains day trip', 'Bondi Beach coastal walk'],
  },
  {
    slug: 'fiji-overwater-honeymoon',
    title: 'Fiji Overwater Honeymoon Bliss',
    destination: 'Fiji', country: 'Fiji',
    image: 'https://picsum.photos/seed/fiji-bure/1200/900',
    duration: '7 nights', nights: 7, price: 2399, originalPrice: 2799,
    airline: 'Fiji Airways', hotel: 'Likuliku Lagoon Resort', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'honeymoon',
    highlights: ['Overwater bure with lagoon access', 'Private sandbank picnic', 'Adults-only tranquil setting'],
  },
  {
    slug: 'amsterdam-canal-city-break',
    title: 'Amsterdam Canal City Break',
    destination: 'Amsterdam', country: 'Netherlands',
    image: 'https://picsum.photos/seed/amsterdam-hotel/1200/900',
    duration: '3 nights', nights: 3, price: 319, originalPrice: 379,
    airline: 'KLM', hotel: 'Pulitzer Amsterdam', hotelStars: 4, board: 'Bed & Breakfast', transfers: false,
    category: 'city',
    highlights: ['Canal-side boutique hotel', 'Van Gogh Museum skip-the-line tickets', 'Evening canal cruise included'],
  },
  {
    slug: 'prague-fairytale-getaway',
    title: 'Prague Fairytale Getaway',
    destination: 'Prague', country: 'Czech Republic',
    image: 'https://picsum.photos/seed/prague-hotel/1200/900',
    duration: '4 nights', nights: 4, price: 369, originalPrice: 429,
    airline: 'Czech Airlines', hotel: 'Aria Hotel Prague', hotelStars: 4, board: 'Bed & Breakfast', transfers: false,
    category: 'city',
    highlights: ['Old Town Square walking tour', 'Prague Castle guided visit', 'Boutique hotel in Malá Strana'],
  },
  {
    slug: 'mauritius-luxury-beach-escape',
    title: 'Mauritius Luxury Beach Escape',
    destination: 'Mauritius', country: 'Mauritius',
    image: 'https://picsum.photos/seed/mauritius-resort/1200/900',
    duration: '8 nights', nights: 8, price: 2199, originalPrice: 2599,
    airline: 'Air Mauritius', hotel: 'One&Only Le Saint Géran', hotelStars: 5, board: 'Half Board', transfers: true,
    category: 'luxury',
    highlights: ['Private beach villa options', 'Indian Ocean water sports included', 'Award-winning spa experience'],
  },
  {
    slug: 'seychelles-honeymoon-paradise',
    title: 'Seychelles Honeymoon Paradise',
    destination: 'Seychelles', country: 'Seychelles',
    image: 'https://picsum.photos/seed/seychelles-villa/1200/900',
    duration: '7 nights', nights: 7, price: 2599, originalPrice: 2999,
    airline: 'Emirates', hotel: 'Four Seasons Resort Seychelles', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'honeymoon',
    highlights: ['Hillside villa with private pool', 'Secluded beach coves', 'Sunset champagne cruise included'],
  },
  {
    slug: 'vietnam-halong-bay-luxury',
    title: 'Vietnam & Halong Bay Luxury Cruise',
    destination: 'Hanoi', country: 'Vietnam',
    image: 'https://picsum.photos/seed/halongbay-cruise/1200/900',
    duration: '8 nights', nights: 8, price: 1699, originalPrice: 1999,
    airline: 'Vietnam Airlines', hotel: 'La Siesta Hanoi + Halong Bay Cruise', hotelStars: 5, board: 'Half Board', transfers: true,
    category: 'luxury',
    highlights: ['Overnight luxury junk boat cruise', 'Hanoi Old Quarter exploration', 'Dramatic limestone karst scenery'],
  },
  {
    slug: 'jamaica-family-beach-resort',
    title: 'Jamaica Family Beach Resort',
    destination: 'Negril', country: 'Jamaica',
    image: 'https://picsum.photos/seed/jamaica-resort/1200/900',
    duration: '7 nights', nights: 7, price: 1399, originalPrice: 1649,
    airline: 'Virgin Atlantic', hotel: 'Beaches Negril Resort', hotelStars: 5, board: 'All-Inclusive', transfers: true,
    category: 'family',
    highlights: ['Kids camp and water park', 'Ultra all-inclusive dining & entertainment', 'Seven-mile white sand beach'],
  },
  {
    slug: 'cape-town-luxury-getaway',
    title: 'Cape Town Luxury Getaway',
    destination: 'Cape Town', country: 'South Africa',
    image: 'https://picsum.photos/seed/capetown-hotel/1200/900',
    duration: '7 nights', nights: 7, price: 1599, originalPrice: 1899,
    airline: 'British Airways', hotel: 'One&Only Cape Town', hotelStars: 5, board: 'Bed & Breakfast', transfers: true,
    category: 'luxury',
    highlights: ['Table Mountain private tour', 'Cape Winelands day excursion', 'Marina-front luxury suite'],
  },
];

export const seedDestinations: Destination[] = [
  { slug: 'tenerife', city: 'Tenerife', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/tenerife-coast/1200/1400', fromPrice: 69, blurb: 'Tenerife keeps the sun going even in a UK winter, with black-sand beaches, whale-watching trips and a volcanic hike up Mount Teide. It’s one of the shortest long-haul-feeling flights from the UK, at under four and a half hours.' },
  { slug: 'sharm-el-sheikh', city: 'Sharm El Sheikh', country: 'Egypt', region: 'middleeast', image: 'https://picsum.photos/seed/sharm-elsheikh/1200/1400', fromPrice: 249, blurb: 'Sharm El Sheikh’s Red Sea reef diving and year-round desert sunshine have made it one of the most consistently booked winter-sun flights from the UK, with direct routes from most major airports.' },
  { slug: 'alicante', city: 'Alicante', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/alicante-coast/1200/1400', fromPrice: 49, blurb: 'Alicante is the classic gateway to the Costa Blanca, with a hilltop castle overlooking the old town and some of Spain’s most reliable beach weather. Direct flights from most UK airports make it an easy, affordable escape.' },
  { slug: 'dubai', city: 'Dubai', country: 'United Arab Emirates', region: 'middleeast', image: 'https://picsum.photos/seed/dubai-skyline/1200/1400', fromPrice: 349, blurb: 'Dubai’s soaring towers, desert excursions and five-star resorts make it one of the most popular long-haul destinations booked from the UK, with a flight time of around seven hours and dozens of daily departures.' },
  { slug: 'new-york', city: 'New York', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/newyork-city/1200/1400', fromPrice: 429, blurb: 'New York needs no introduction, and remains one of the UK’s most-booked transatlantic flight routes, with a flight time of around eight hours from most major airports.' },
  { slug: 'toronto', city: 'Toronto', country: 'Canada', region: 'americas', image: 'https://picsum.photos/seed/toronto-city/1200/1400', fromPrice: 459, blurb: 'Toronto’s cosmopolitan skyline on Lake Ontario is one of the most popular Canadian routes flown from the UK, with strong family and business demand.' },
  { slug: 'bangkok', city: 'Bangkok', country: 'Thailand', region: 'asia', image: 'https://picsum.photos/seed/bangkok-temple/1200/1400', fromPrice: 499, blurb: 'Bangkok’s ornate temples and electric street food scene make it the classic gateway to Southeast Asia, typically flown from the UK via a one-stop or direct route of around eleven to twelve hours.' },
  { slug: 'istanbul', city: 'Istanbul', country: 'Turkey', region: 'europe', image: 'https://picsum.photos/seed/istanbul-mosque/1200/1400', fromPrice: 189, blurb: 'Istanbul straddles Europe and Asia across the Bosphorus, its skyline of domes and minarets backed by grand bazaars and centuries of Ottoman and Byzantine history. Turkish Airlines runs frequent flights from the UK, making a city break here surprisingly easy to plan.' },
  { slug: 'lahore', city: 'Lahore', country: 'Pakistan', region: 'asia', image: 'https://picsum.photos/seed/lahore-fort/1200/1400', fromPrice: 419, blurb: 'Lahore’s Mughal-era forts, gardens and legendary hospitality make it one of the most-flown routes from the UK thanks to a large diaspora community, with several airlines offering direct or one-stop connections.' },
  { slug: 'islamabad', city: 'Islamabad', country: 'Pakistan', region: 'asia', image: 'https://picsum.photos/seed/islamabad-hills/1200/1400', fromPrice: 419, blurb: 'Islamabad, framed by the Margalla Hills, is Pakistan’s calmer, greener capital and a well-served route from the UK for both visiting family and exploring the north.' },
  { slug: 'karachi', city: 'Karachi', country: 'Pakistan', region: 'asia', image: 'https://picsum.photos/seed/karachi-coast/1200/1400', fromPrice: 399, blurb: 'Karachi’s coastal energy on the Arabian Sea makes it Pakistan’s largest city and one of its busiest flight routes from the UK, with several direct services available.' },
  { slug: 'paris', city: 'Paris', country: 'France', region: 'europe', image: 'https://picsum.photos/seed/paris-eiffel/1200/1400', fromPrice: 79, blurb: 'Paris needs little introduction — the Eiffel Tower, the Louvre and café culture along the Seine, all reachable on flights from the UK in barely over an hour. It remains one of the most booked short-haul city breaks for British travellers.' },
  { slug: 'rome', city: 'Rome', country: 'Italy', region: 'europe', image: 'https://picsum.photos/seed/rome-colosseum/1200/1400', fromPrice: 89, blurb: 'Rome layers three thousand years of history into a walkable city, from the Colosseum and Roman Forum to Renaissance piazzas and unbeatable pasta. Flights from the UK take around two and a half hours, making it a strong choice for a long weekend.' },
  { slug: 'maldives', city: 'Maldives', country: 'Maldives', region: 'asia', image: 'https://picsum.photos/seed/maldives-overwater/1200/1400', fromPrice: 899, blurb: 'The Maldives’ overwater villas above impossibly turquoise water make it one of the UK’s most-booked honeymoon and luxury flight destinations, usually reached via a stopover in the Gulf.' },
  { slug: 'bali', city: 'Bali', country: 'Indonesia', region: 'asia', image: 'https://picsum.photos/seed/bali-rice/1200/1400', fromPrice: 749, blurb: 'Bali’s emerald rice terraces and beach culture have made it one of the most sought-after long-haul flights from the UK, typically via a stop in the Gulf or Southeast Asia.' },
  { slug: 'phuket', city: 'Phuket', country: 'Thailand', region: 'asia', image: 'https://picsum.photos/seed/phuket-beach/1200/1400', fromPrice: 619, blurb: 'Phuket’s Andaman Sea beaches and resort choice for every budget make it Thailand’s most-booked beach flight from the UK, often paired with a Bangkok stopover.' },
  { slug: 'antalya', city: 'Antalya', country: 'Turkey', region: 'europe', image: 'https://picsum.photos/seed/antalya-coast/1200/1400', fromPrice: 159, blurb: 'Antalya delivers Turquoise Coast luxury — cliffside resorts, waterfalls and Roman ruins — at a fraction of the price of Western Europe. It’s become one of the fastest-growing beach destinations booked from the UK in recent years.' },
  { slug: 'vancouver', city: 'Vancouver', country: 'Canada', region: 'americas', image: 'https://picsum.photos/seed/vancouver-mountains/1200/1400', fromPrice: 479, blurb: 'Vancouver, where mountains meet ocean on Canada’s west coast, is typically flown from the UK on a direct service of around nine and a half hours.' },
  { slug: 'orlando', city: 'Orlando', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/orlando-parks/1200/1400', fromPrice: 449, blurb: 'Orlando’s theme parks make it one of the UK’s most-booked family flight routes, with direct services running from several UK airports, especially in school holidays.' },
  { slug: 'sydney', city: 'Sydney', country: 'Australia', region: 'oceania', image: 'https://picsum.photos/seed/sydney-harbour/1200/1400', fromPrice: 799, blurb: 'Sydney’s harbour views and golden beaches make it Australia’s most iconic long-haul flight from the UK, typically around twenty-two hours with a stopover.' },

  { slug: 'faro', city: 'Faro', country: 'Portugal', region: 'europe', image: 'https://picsum.photos/seed/faro-algarve/1200/1400', fromPrice: 55, blurb: 'Faro is the gateway to the Algarve’s golden cliffs, sea caves and beach towns like Lagos and Albufeira. It’s a well-worn favourite for UK holidaymakers, with a flight time of under three hours.' },
  { slug: 'gran-canaria', city: 'Gran Canaria', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/grancanaria-dunes/1200/1400', fromPrice: 75, blurb: 'Gran Canaria packs dunes, mountains and beach resorts onto a single Canary Island, earning it the nickname ’a miniature continent’. Direct flights from the UK run year-round, making it a reliable winter-sun choice.' },

  // --- Europe ---
  { slug: 'barcelona', city: 'Barcelona', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/barcelona-city/1200/1400', fromPrice: 59, blurb: 'Barcelona pairs Gaudí’s extraordinary architecture with Mediterranean beach life, tapas bars and buzzing Las Ramblas. It’s consistently one of the most popular city-break flights booked from the UK.' },
  { slug: 'madrid', city: 'Madrid', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/madrid-city/1200/1400', fromPrice: 65, blurb: 'Madrid offers grand boulevards, world-class art at the Prado and a tapas culture that runs late into the night. Flights from the UK take around two and a half hours, making it an easy weekend trip.' },
  { slug: 'amsterdam', city: 'Amsterdam', country: 'Netherlands', region: 'europe', image: 'https://picsum.photos/seed/amsterdam-canals/1200/1400', fromPrice: 45, blurb: 'Amsterdam’s canal-ringed centre, world-class museums and cycling culture make it one of the most walkable city breaks in Europe. It’s under an hour and a half by air from most UK airports.' },
  { slug: 'berlin', city: 'Berlin', country: 'Germany', region: 'europe', image: 'https://picsum.photos/seed/berlin-city/1200/1400', fromPrice: 55, blurb: 'Berlin mixes heavyweight history — the Wall, the Brandenburg Gate — with some of Europe’s best nightlife and art scenes. Flights from the UK are frequent and typically under two hours.' },
  { slug: 'munich', city: 'Munich', country: 'Germany', region: 'europe', image: 'https://picsum.photos/seed/munich-city/1200/1400', fromPrice: 69, blurb: 'Munich blends Bavarian tradition with Alpine views on the doorstep, from beer halls to day trips into the mountains. It’s a popular gateway for both city breaks and skiing trips from the UK.' },
  { slug: 'frankfurt', city: 'Frankfurt', country: 'Germany', region: 'europe', image: 'https://picsum.photos/seed/frankfurt-skyline/1200/1400', fromPrice: 59, blurb: 'Frankfurt’s glass-and-steel skyline sits above a historic old town on the river Main, and its major hub airport makes it one of the most connected cities in Europe for UK travellers.' },
  { slug: 'vienna', city: 'Vienna', country: 'Austria', region: 'europe', image: 'https://picsum.photos/seed/vienna-city/1200/1400', fromPrice: 75, blurb: 'Vienna’s imperial palaces, coffee house culture and classical music heritage make it one of Europe’s grandest city breaks. Flights from the UK run in around two hours.' },
  { slug: 'prague', city: 'Prague', country: 'Czech Republic', region: 'europe', image: 'https://picsum.photos/seed/prague-city/1200/1400', fromPrice: 49, blurb: 'Prague’s fairytale spires and cobbled old town above the Vltava River have made it one of the most photographed cities in Europe, and one of the cheapest short-haul flights from the UK.' },
  { slug: 'budapest', city: 'Budapest', country: 'Hungary', region: 'europe', image: 'https://picsum.photos/seed/budapest-city/1200/1400', fromPrice: 45, blurb: 'Budapest pairs grand Danube-side architecture with thermal baths that let you soak year-round. It’s a strong-value city break, typically under two and a half hours from the UK by air.' },
  { slug: 'lisbon', city: 'Lisbon', country: 'Portugal', region: 'europe', image: 'https://picsum.photos/seed/lisbon-city/1200/1400', fromPrice: 69, blurb: 'Lisbon’s pastel hillsides, vintage trams and golden Atlantic light have made it one of Europe’s most in-demand city breaks in recent years, with flights from the UK taking around two and a half hours.' },
  { slug: 'porto', city: 'Porto', country: 'Portugal', region: 'europe', image: 'https://picsum.photos/seed/porto-city/1200/1400', fromPrice: 59, blurb: 'Porto’s riverside old town and centuries-old port wine cellars offer a quieter, more affordable alternative to Lisbon, with a similar flight time from the UK.' },
  { slug: 'milan', city: 'Milan', country: 'Italy', region: 'europe', image: 'https://picsum.photos/seed/milan-city/1200/1400', fromPrice: 55, blurb: 'Milan is Italy’s fashion and design capital, with world-class shopping, the Duomo and some of the country’s best restaurants. It’s a popular short flight from the UK for both leisure and business travellers.' },
  { slug: 'venice', city: 'Venice', country: 'Italy', region: 'europe', image: 'https://picsum.photos/seed/venice-canals/1200/1400', fromPrice: 65, blurb: 'Venice’s canals and gondolas make it unlike anywhere else on earth — a city built entirely on water, with flights from the UK landing you within reach of St Mark’s Square in under two hours.' },
  { slug: 'florence', city: 'Florence', country: 'Italy', region: 'europe', image: 'https://picsum.photos/seed/florence-city/1200/1400', fromPrice: 69, blurb: 'Florence is the cradle of the Renaissance, with Michelangelo’s David, the Uffizi Gallery and Tuscan countryside all within easy reach. It’s a favourite add-on to an Italian multi-city trip from the UK.' },
  { slug: 'athens', city: 'Athens', country: 'Greece', region: 'europe', image: 'https://picsum.photos/seed/athens-acropolis/1200/1400', fromPrice: 89, blurb: 'Athens sits beneath the Acropolis, with ancient ruins woven directly into the modern city and easy onward ferries to the Greek islands. Flights from the UK take around three and a half hours.' },
  { slug: 'santorini', city: 'Santorini', country: 'Greece', region: 'europe', image: 'https://picsum.photos/seed/santorini-caldera/1200/1400', fromPrice: 129, blurb: 'Santorini’s whitewashed cliffside villages above a volcanic caldera make it one of the most photographed islands in the world, and a hugely popular honeymoon destination booked from the UK.' },
  { slug: 'mykonos', city: 'Mykonos', country: 'Greece', region: 'europe', image: 'https://picsum.photos/seed/mykonos-island/1200/1400', fromPrice: 135, blurb: 'Mykonos combines windmill-lined harbours with some of the Mediterranean’s best beach clubs, drawing UK travellers looking for an Aegean island break with serious nightlife.' },
  { slug: 'zurich', city: 'Zurich', country: 'Switzerland', region: 'europe', image: 'https://picsum.photos/seed/zurich-city/1200/1400', fromPrice: 89, blurb: 'Zurich’s lakeside elegance sits at the foot of the Alps, making it a popular gateway for both city breaks and Swiss mountain trips from the UK.' },
  { slug: 'geneva', city: 'Geneva', country: 'Switzerland', region: 'europe', image: 'https://picsum.photos/seed/geneva-lake/1200/1400', fromPrice: 85, blurb: 'Geneva offers a refined, lakeside introduction to Switzerland, and is one of the main UK flight routes into the Alps for skiing and summer hiking alike.' },
  { slug: 'brussels', city: 'Brussels', country: 'Belgium', region: 'europe', image: 'https://picsum.photos/seed/brussels-city/1200/1400', fromPrice: 39, blurb: 'Brussels’ grand squares, chocolate shops and easy-going pace make it one of the shortest possible flights (or a train ride) from the UK for a European city break.' },
  { slug: 'copenhagen', city: 'Copenhagen', country: 'Denmark', region: 'europe', image: 'https://picsum.photos/seed/copenhagen-city/1200/1400', fromPrice: 79, blurb: 'Copenhagen’s Scandinavian design, colourful harbourfronts and cycling culture have made it one of Northern Europe’s most in-demand city breaks from the UK.' },
  { slug: 'stockholm', city: 'Stockholm', country: 'Sweden', region: 'europe', image: 'https://picsum.photos/seed/stockholm-city/1200/1400', fromPrice: 89, blurb: 'Stockholm is built across fourteen islands, giving it more waterfront than almost any other European capital — a straightforward flight of around two and a half hours from the UK.' },
  { slug: 'oslo', city: 'Oslo', country: 'Norway', region: 'europe', image: 'https://picsum.photos/seed/oslo-fjord/1200/1400', fromPrice: 95, blurb: 'Oslo pairs fjord views with Scandinavian minimalism, and serves as a natural starting point for exploring Norway’s fjords on a longer trip from the UK.' },
  { slug: 'reykjavik', city: 'Reykjavik', country: 'Iceland', region: 'europe', image: 'https://picsum.photos/seed/reykjavik-city/1200/1400', fromPrice: 149, blurb: 'Reykjavik is the gateway to the Northern Lights, hot springs and volcanic landscapes, and one of the fastest-growing short-haul destinations booked from the UK in recent years.' },
  { slug: 'dublin', city: 'Dublin', country: 'Ireland', region: 'europe', image: 'https://picsum.photos/seed/dublin-city/1200/1400', fromPrice: 35, blurb: 'Dublin’s literary pubs and easy Irish hospitality make it one of the quickest possible breaks from the UK, with flights from most regional airports taking under an hour.' },
  { slug: 'nice', city: 'Nice', country: 'France', region: 'europe', image: 'https://picsum.photos/seed/nice-riviera/1200/1400', fromPrice: 65, blurb: 'Nice puts the French Riviera within reach of a short flight from the UK, with the Promenade des Anglais, the old town and Monaco all close by.' },
  { slug: 'malaga', city: 'Malaga', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/malaga-coast/1200/1400', fromPrice: 55, blurb: 'Malaga is the gateway to the Costa del Sol’s golden beaches, with a historic centre and Picasso’s birthplace thrown in. It’s one of the most-flown Spanish routes from the UK.' },
  { slug: 'palma-de-mallorca', city: 'Palma de Mallorca', country: 'Spain', region: 'europe', image: 'https://picsum.photos/seed/palma-mallorca/1200/1400', fromPrice: 59, blurb: 'Palma de Mallorca combines Balearic beach resorts with a genuinely historic old town and cathedral, making it a favourite for both families and couples flying from the UK.' },

  // --- Middle East & North Africa ---
  { slug: 'abu-dhabi', city: 'Abu Dhabi', country: 'United Arab Emirates', region: 'middleeast', image: 'https://picsum.photos/seed/abudhabi-skyline/1200/1400', fromPrice: 379, blurb: 'Abu Dhabi offers grand mosques, Formula 1 and desert luxury on the Gulf, as a slightly quieter, more traditional alternative to neighbouring Dubai for UK travellers.' },
  { slug: 'doha', city: 'Doha', country: 'Qatar', region: 'middleeast', image: 'https://picsum.photos/seed/doha-skyline/1200/1400', fromPrice: 359, blurb: 'Doha’s futuristic skyline on the Arabian Gulf has become one of the busiest stopover and destination cities for UK travellers flying east, thanks to Qatar Airways’ extensive route network.' },
  { slug: 'muscat', city: 'Muscat', country: 'Oman', region: 'middleeast', image: 'https://picsum.photos/seed/muscat-city/1200/1400', fromPrice: 399, blurb: 'Muscat’s whitewashed forts and dramatic desert mountains offer a quieter, more traditional side of the Gulf, popular with UK travellers looking to combine culture with coastal luxury.' },
  { slug: 'riyadh', city: 'Riyadh', country: 'Saudi Arabia', region: 'middleeast', image: 'https://picsum.photos/seed/riyadh-skyline/1200/1400', fromPrice: 389, blurb: 'Riyadh is a capital transforming at extraordinary pace, with new direct flight routes from the UK opening up Saudi Arabia’s business and cultural centre.' },
  { slug: 'jeddah', city: 'Jeddah', country: 'Saudi Arabia', region: 'middleeast', image: 'https://picsum.photos/seed/jeddah-corniche/1200/1400', fromPrice: 399, blurb: 'Jeddah’s historic Red Sea corniche and old town make it both a business hub and the main gateway for pilgrims flying from the UK to Mecca and Medina.' },
  { slug: 'manama', city: 'Manama', country: 'Bahrain', region: 'middleeast', image: 'https://picsum.photos/seed/manama-skyline/1200/1400', fromPrice: 369, blurb: 'Manama is a compact island capital rich in pearl-diving history, easily combined with a wider Gulf itinerary on flights from the UK.' },
  { slug: 'amman', city: 'Amman', country: 'Jordan', region: 'middleeast', image: 'https://picsum.photos/seed/amman-city/1200/1400', fromPrice: 329, blurb: 'Amman is the natural gateway to Petra and the ancient Levant, with UK flights typically routing through for a Jordan itinerary covering the Dead Sea and Wadi Rum.' },
  { slug: 'beirut', city: 'Beirut', country: 'Lebanon', region: 'middleeast', image: 'https://picsum.photos/seed/beirut-city/1200/1400', fromPrice: 349, blurb: 'Beirut layers Mediterranean energy over deep history, from Roman ruins to a legendary food and nightlife scene, drawing a strong diaspora market of flights from the UK.' },
  { slug: 'tel-aviv', city: 'Tel Aviv', country: 'Israel', region: 'middleeast', image: 'https://picsum.photos/seed/telaviv-beach/1200/1400', fromPrice: 299, blurb: 'Tel Aviv brings beach-city energy to the eastern Mediterranean, with a flight time of around five hours from the UK and a reputation as one of the region’s most cosmopolitan cities.' },
  { slug: 'cairo', city: 'Cairo', country: 'Egypt', region: 'middleeast', image: 'https://picsum.photos/seed/cairo-pyramids/1200/1400', fromPrice: 279, blurb: 'Cairo puts the pyramids of Giza on the edge of a sprawling mega-city, and remains one of the most-booked cultural flights from the UK to North Africa.' },
  { slug: 'marrakech', city: 'Marrakech', country: 'Morocco', region: 'middleeast', image: 'https://picsum.photos/seed/marrakech-medina/1200/1400', fromPrice: 99, blurb: 'Marrakech’s souks, riads and the Atlas Mountains beyond have made it one of the most popular short-haul flights from the UK for a taste of North Africa, at under four hours’ flying time.' },
  { slug: 'hurghada', city: 'Hurghada', country: 'Egypt', region: 'middleeast', image: 'https://picsum.photos/seed/hurghada-redsea/1200/1400', fromPrice: 219, blurb: 'Hurghada’s Red Sea reefs and year-round desert sunshine make it a reliable winter-sun choice, with direct charter and scheduled flights from most UK airports.' },

  // --- Asia ---
  { slug: 'singapore', city: 'Singapore', country: 'Singapore', region: 'asia', image: 'https://picsum.photos/seed/singapore-skyline/1200/1400', fromPrice: 549, blurb: 'Singapore’s gleaming skyline and position at the crossroads of Asia make it both a destination in its own right and a popular stopover on longer UK flights to Australia and New Zealand.' },
  { slug: 'kuala-lumpur', city: 'Kuala Lumpur', country: 'Malaysia', region: 'asia', image: 'https://picsum.photos/seed/kualalumpur-towers/1200/1400', fromPrice: 499, blurb: 'Kuala Lumpur’s Petronas Towers and melting-pot food scene sit on one of the more affordable long-haul routes from the UK to Southeast Asia.' },
  { slug: 'hong-kong', city: 'Hong Kong', country: 'Hong Kong', region: 'asia', image: 'https://picsum.photos/seed/hongkong-skyline/1200/1400', fromPrice: 579, blurb: 'Hong Kong’s dazzling harbour skyline is reachable on a direct flight of around twelve hours from the UK, combining big-city energy with easy access to mainland China.' },
  { slug: 'tokyo', city: 'Tokyo', country: 'Japan', region: 'asia', image: 'https://picsum.photos/seed/tokyo-shibuya/1200/1400', fromPrice: 649, blurb: 'Tokyo’s neon streets and ancient shrines sit side by side in a city UK travellers have been booking in growing numbers, with direct flights now running from Heathrow.' },
  { slug: 'osaka', city: 'Osaka', country: 'Japan', region: 'asia', image: 'https://picsum.photos/seed/osaka-castle/1200/1400', fromPrice: 679, blurb: 'Osaka, Japan’s food capital, offers a warmer, more relaxed alternative to Tokyo, usually reached from the UK via a connection through a major Asian hub.' },
  { slug: 'seoul', city: 'Seoul', country: 'South Korea', region: 'asia', image: 'https://picsum.photos/seed/seoul-city/1200/1400', fromPrice: 619, blurb: 'Seoul’s ancient palaces beside a hyper-modern skyline have made it one of the fastest-growing Asian destinations booked from the UK in recent years.' },
  { slug: 'beijing', city: 'Beijing', country: 'China', region: 'asia', image: 'https://picsum.photos/seed/beijing-city/1200/1400', fromPrice: 549, blurb: 'Beijing puts the Great Wall and centuries of imperial history within reach of a direct flight from the UK of around ten hours.' },
  { slug: 'shanghai', city: 'Shanghai', country: 'China', region: 'asia', image: 'https://picsum.photos/seed/shanghai-skyline/1200/1400', fromPrice: 569, blurb: 'Shanghai’s futuristic skyline above the historic Bund makes it one of the most striking direct long-haul flights from the UK.' },
  { slug: 'delhi', city: 'Delhi', country: 'India', region: 'asia', image: 'https://picsum.photos/seed/delhi-city/1200/1400', fromPrice: 449, blurb: 'Delhi’s Mughal monuments sit inside a vast, vibrant capital, and remains one of the busiest India routes flown from the UK thanks to strong family and business demand.' },
  { slug: 'mumbai', city: 'Mumbai', country: 'India', region: 'asia', image: 'https://picsum.photos/seed/mumbai-city/1200/1400', fromPrice: 469, blurb: 'Mumbai, India’s coastal city of dreams, is one of the most-flown long-haul routes from the UK, with multiple daily direct departures.' },
  { slug: 'colombo', city: 'Colombo', country: 'Sri Lanka', region: 'asia', image: 'https://picsum.photos/seed/colombo-city/1200/1400', fromPrice: 529, blurb: 'Colombo is the tropical gateway to Sri Lanka’s tea country and ancient temples, typically flown from the UK via a one-stop connection.' },
  { slug: 'ho-chi-minh-city', city: 'Ho Chi Minh City', country: 'Vietnam', region: 'asia', image: 'https://picsum.photos/seed/hochiminh-city/1200/1400', fromPrice: 559, blurb: 'Ho Chi Minh City’s motorbike energy and street food scene make it a growing long-haul destination booked from the UK, usually via a stop in the Gulf or East Asia.' },
  { slug: 'hanoi', city: 'Hanoi', country: 'Vietnam', region: 'asia', image: 'https://picsum.photos/seed/hanoi-city/1200/1400', fromPrice: 549, blurb: 'Hanoi’s Old Quarter and easy access to Halong Bay make it a popular starting point for a Vietnam trip flown from the UK.' },
  { slug: 'manila', city: 'Manila', country: 'Philippines', region: 'asia', image: 'https://picsum.photos/seed/manila-city/1200/1400', fromPrice: 599, blurb: 'Manila is the vibrant gateway to the Philippines’ 7,000 islands, usually reached from the UK via a connection through the Gulf or Hong Kong.' },
  { slug: 'jakarta', city: 'Jakarta', country: 'Indonesia', region: 'asia', image: 'https://picsum.photos/seed/jakarta-city/1200/1400', fromPrice: 589, blurb: 'Jakarta, at the heart of the Indonesian archipelago, is a major business and transit route flown from the UK into Southeast Asia.' },
  { slug: 'kathmandu', city: 'Kathmandu', country: 'Nepal', region: 'asia', image: 'https://picsum.photos/seed/kathmandu-city/1200/1400', fromPrice: 599, blurb: 'Kathmandu, framed by Himalayan peaks, is the starting point for trekking trips booked from the UK, usually flown via a connection through the Gulf or India.' },

  // --- Americas ---
  { slug: 'los-angeles', city: 'Los Angeles', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/losangeles-city/1200/1400', fromPrice: 449, blurb: 'Los Angeles’ sunshine, studios and Pacific coastline make it a consistently popular direct flight from the UK, at around eleven hours.' },
  { slug: 'san-francisco', city: 'San Francisco', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/sanfrancisco-bay/1200/1400', fromPrice: 469, blurb: 'San Francisco’s fog-kissed hills above the Golden Gate Bridge are reachable on a direct flight from the UK of around eleven hours.' },
  { slug: 'chicago', city: 'Chicago', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/chicago-skyline/1200/1400', fromPrice: 419, blurb: 'Chicago’s bold architecture on the shores of Lake Michigan is a well-served direct route from several UK airports.' },
  { slug: 'miami', city: 'Miami', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/miami-beach/1200/1400', fromPrice: 399, blurb: 'Miami’s art deco glamour and beach energy make it one of the most-booked Florida flights from the UK, often paired with a Caribbean cruise.' },
  { slug: 'las-vegas', city: 'Las Vegas', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/lasvegas-strip/1200/1400', fromPrice: 459, blurb: 'Las Vegas’ non-stop entertainment on the Strip is a direct flight of around ten hours from the UK, and a popular stop on a wider US road trip.' },
  { slug: 'boston', city: 'Boston', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/boston-city/1200/1400', fromPrice: 389, blurb: 'Boston’s colonial history along a walkable waterfront makes it a popular shorter-haul alternative to New York, flown direct from several UK airports.' },
  { slug: 'washington-dc', city: 'Washington DC', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/washingtondc-monuments/1200/1400', fromPrice: 409, blurb: 'Washington DC’s monuments and museums sit at the seat of a nation, and it’s flown direct from the UK on services of around eight hours.' },
  { slug: 'cancun', city: 'Cancun', country: 'Mexico', region: 'americas', image: 'https://picsum.photos/seed/cancun-beach/1200/1400', fromPrice: 549, blurb: 'Cancun’s Caribbean waters and nearby Mayan ruins make it one of the UK’s most-booked long-haul beach flights, especially for winter sun.' },
  { slug: 'mexico-city', city: 'Mexico City', country: 'Mexico', region: 'americas', image: 'https://picsum.photos/seed/mexicocity-city/1200/1400', fromPrice: 499, blurb: 'Mexico City’s Aztec history sits beneath a vast, colourful capital, usually reached from the UK via a connecting flight through the US or Europe.' },
  { slug: 'rio-de-janeiro', city: 'Rio de Janeiro', country: 'Brazil', region: 'americas', image: 'https://picsum.photos/seed/rio-copacabana/1200/1400', fromPrice: 599, blurb: 'Rio de Janeiro, watched over by Christ the Redeemer, is South America’s most iconic flight destination from the UK, typically via a one-stop route.' },
  { slug: 'buenos-aires', city: 'Buenos Aires', country: 'Argentina', region: 'americas', image: 'https://picsum.photos/seed/buenosaires-city/1200/1400', fromPrice: 649, blurb: 'Buenos Aires’ tango, steakhouses and grand European-style boulevards make it one of the longest-haul but most rewarding South American flights from the UK.' },
  { slug: 'lima', city: 'Lima', country: 'Peru', region: 'americas', image: 'https://picsum.photos/seed/lima-city/1200/1400', fromPrice: 599, blurb: 'Lima, Peru’s coastal capital, is the usual gateway flight from the UK for travellers heading onward to Machu Picchu.' },
  { slug: 'kingston-jamaica', city: 'Kingston', country: 'Jamaica', region: 'americas', image: 'https://picsum.photos/seed/kingston-jamaica/1200/1400', fromPrice: 579, blurb: 'Kingston’s reggae roots and lush Caribbean mountains draw a strong diaspora flight market from the UK, with several direct and one-stop options.' },
  { slug: 'nassau-bahamas', city: 'Nassau', country: 'Bahamas', region: 'americas', image: 'https://picsum.photos/seed/nassau-bahamas/1200/1400', fromPrice: 599, blurb: 'Nassau’s powder-white sands across turquoise shallows make it a popular add-on to a Florida or Caribbean cruise flight from the UK.' },
  { slug: 'bridgetown-barbados', city: 'Bridgetown', country: 'Barbados', region: 'americas', image: 'https://picsum.photos/seed/bridgetown-barbados/1200/1400', fromPrice: 549, blurb: 'Bridgetown, Barbados’ friendly Caribbean capital, is one of the UK’s best-connected Caribbean routes, with direct flights from several UK airports.' },
  { slug: 'montreal', city: 'Montreal', country: 'Canada', region: 'americas', image: 'https://picsum.photos/seed/montreal-city/1200/1400', fromPrice: 429, blurb: 'Montreal’s French joie de vivre on the St Lawrence River is a direct flight from the UK of around seven and a half hours.' },
  { slug: 'punta-cana', city: 'Punta Cana', country: 'Dominican Republic', region: 'americas', image: 'https://picsum.photos/seed/puntacana-beach/1200/1400', fromPrice: 649, blurb: 'Punta Cana’s miles of white-sand, all-inclusive coastline have made it one of the fastest-growing Caribbean flight routes booked from the UK.' },
  { slug: 'havana', city: 'Havana', country: 'Cuba', region: 'americas', image: 'https://picsum.photos/seed/havana-city/1200/1400', fromPrice: 629, blurb: 'Havana’s vintage cars and live music on colonial streets make it one of the Caribbean’s most distinctive flight destinations from the UK, usually via a one-stop route.' },
  { slug: 'antigua', city: 'St John’s', country: 'Antigua and Barbuda', region: 'americas', image: 'https://picsum.photos/seed/antigua-beach/1200/1400', fromPrice: 599, blurb: 'Antigua’s claim to ’a beach for every day of the year’ makes it one of the most sought-after direct Caribbean flights from the UK.' },
  { slug: 'st-lucia', city: 'Castries', country: 'St Lucia', region: 'americas', image: 'https://picsum.photos/seed/stlucia-pitons/1200/1400', fromPrice: 649, blurb: 'St Lucia’s Pitons rising from turquoise bays make it one of the Caribbean’s most photographed honeymoon flights booked from the UK.' },
  { slug: 'aruba', city: 'Oranjestad', country: 'Aruba', region: 'americas', image: 'https://picsum.photos/seed/aruba-beach/1200/1400', fromPrice: 679, blurb: 'Aruba, known as ’One Happy Island’, is reliably outside the Caribbean hurricane belt, making it a popular winter flight choice from the UK.' },
  { slug: 'bogota', city: 'Bogotá', country: 'Colombia', region: 'americas', image: 'https://picsum.photos/seed/bogota-city/1200/1400', fromPrice: 549, blurb: 'Bogotá’s high-altitude capital of street art and salsa is usually flown from the UK via a one-stop connection through the US or Europe.' },
  { slug: 'panama-city', city: 'Panama City', country: 'Panama', region: 'americas', image: 'https://picsum.photos/seed/panamacity-skyline/1200/1400', fromPrice: 579, blurb: 'Panama City’s gleaming skyline beside the historic canal is a growing long-haul flight route from the UK, often combined with a Central America itinerary.' },
  { slug: 'san-diego', city: 'San Diego', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/sandiego-coast/1200/1400', fromPrice: 459, blurb: 'San Diego’s laid-back Pacific coast sunshine is typically flown from the UK via a connection, and pairs well with a wider California itinerary.' },
  { slug: 'seattle', city: 'Seattle', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/seattle-skyline/1200/1400', fromPrice: 439, blurb: 'Seattle’s coffee culture beneath the Space Needle is served by direct flights from the UK of around nine and a half hours.' },
  { slug: 'new-orleans', city: 'New Orleans', country: 'United States', region: 'americas', image: 'https://picsum.photos/seed/neworleans-quarter/1200/1400', fromPrice: 429, blurb: 'New Orleans’ jazz, jambalaya and French Quarter charm make it a distinctive US flight route from the UK, usually via a connection.' },

  // --- Africa ---
  { slug: 'cape-town', city: 'Cape Town', country: 'South Africa', region: 'africa', image: 'https://picsum.photos/seed/capetown-tablemountain/1200/1400', fromPrice: 549, blurb: 'Cape Town pairs Table Mountain and the Cape Winelands with a dramatic coastline, and is one of the UK’s most popular long-haul flights for a South Africa trip, at around eleven hours direct.' },
  { slug: 'johannesburg', city: 'Johannesburg', country: 'South Africa', region: 'africa', image: 'https://picsum.photos/seed/johannesburg-city/1200/1400', fromPrice: 499, blurb: 'Johannesburg is the main UK gateway to safari country, with direct flights of around eleven hours and easy onward connections to Kruger National Park.' },
  { slug: 'nairobi', city: 'Nairobi', country: 'Kenya', region: 'africa', image: 'https://picsum.photos/seed/nairobi-city/1200/1400', fromPrice: 479, blurb: 'Nairobi, the safari capital, puts wildlife on the city’s doorstep, and is typically flown direct from the UK on an overnight service of around eight and a half hours.' },
  { slug: 'zanzibar', city: 'Zanzibar', country: 'Tanzania', region: 'africa', image: 'https://picsum.photos/seed/zanzibar-beach/1200/1400', fromPrice: 599, blurb: 'Zanzibar’s spice-island beaches and centuries-old Stone Town make it one of the fastest-growing long-haul flights from the UK, often combined with a Tanzania safari.' },
  { slug: 'mombasa', city: 'Mombasa', country: 'Kenya', region: 'africa', image: 'https://picsum.photos/seed/mombasa-coast/1200/1400', fromPrice: 519, blurb: 'Mombasa’s Indian Ocean beaches and Swahili coast heritage make it a popular beach-and-safari combination flight from the UK, usually via a stop in the Gulf.' },
  { slug: 'mauritius', city: 'Mauritius', country: 'Mauritius', region: 'africa', image: 'https://picsum.photos/seed/mauritius-lagoon/1200/1400', fromPrice: 799, blurb: 'Mauritius’ lagoon-blue water and honeymoon-perfect resorts make it one of the UK’s most in-demand luxury long-haul flights, typically around eleven to twelve hours.' },
  { slug: 'seychelles', city: 'Victoria', country: 'Seychelles', region: 'africa', image: 'https://picsum.photos/seed/seychelles-beach/1200/1400', fromPrice: 849, blurb: 'The Seychelles’ granite boulders and powder-soft sand offer an exclusive, private-island feel, and remain one of the UK’s premium honeymoon flight routes.' },
  { slug: 'lagos', city: 'Lagos', country: 'Nigeria', region: 'africa', image: 'https://picsum.photos/seed/lagos-city/1200/1400', fromPrice: 449, blurb: 'Lagos, West Africa’s buzzing commercial and cultural capital, is one of the UK’s busiest African flight routes thanks to a large diaspora community, with several direct daily services.' },
  { slug: 'accra', city: 'Accra', country: 'Ghana', region: 'africa', image: 'https://picsum.photos/seed/accra-city/1200/1400', fromPrice: 439, blurb: 'Accra’s coastal forts and vibrant markets on the Gulf of Guinea make it a well-served direct flight route from the UK, particularly popular around the December festive season.' },
  { slug: 'addis-ababa', city: 'Addis Ababa', country: 'Ethiopia', region: 'africa', image: 'https://picsum.photos/seed/addisababa-city/1200/1400', fromPrice: 469, blurb: 'Addis Ababa, a high-altitude capital and gateway to ancient Ethiopian history, is a major hub for Ethiopian Airlines’ network, well connected from the UK with onward links across Africa.' },

  // --- Oceania ---
  { slug: 'auckland', city: 'Auckland', country: 'New Zealand', region: 'oceania', image: 'https://picsum.photos/seed/auckland-harbour/1200/1400', fromPrice: 949, blurb: 'Auckland, a city of sails between two shimmering harbours, is usually flown from the UK via a stopover in Asia or the Middle East, given its distance of over 24 hours’ flying time.' },
  { slug: 'melbourne', city: 'Melbourne', country: 'Australia', region: 'oceania', image: 'https://picsum.photos/seed/melbourne-city/1200/1400', fromPrice: 799, blurb: 'Melbourne’s laneway culture, coffee and world-class sport make it a favourite long-haul flight from the UK for extended stays and working holidays.' },
  { slug: 'brisbane', city: 'Brisbane', country: 'Australia', region: 'oceania', image: 'https://picsum.photos/seed/brisbane-river/1200/1400', fromPrice: 819, blurb: 'Brisbane’s riverside sunshine and gateway position to the Gold Coast make it a popular long-haul flight choice from the UK for a warmer Australian climate.' },
  { slug: 'perth', city: 'Perth', country: 'Australia', region: 'oceania', image: 'https://picsum.photos/seed/perth-city/1200/1400', fromPrice: 749, blurb: 'Perth’s wide skies and pristine west-coast beaches make it the closest Australian city to fly to from the UK, though still a considerable long-haul journey.' },
  { slug: 'nadi-fiji', city: 'Nadi', country: 'Fiji', region: 'oceania', image: 'https://picsum.photos/seed/nadi-fiji/1200/1400', fromPrice: 899, blurb: 'Nadi is the gateway to Fiji’s scattered island paradise, usually flown from the UK via a stopover in the US or Australia given its remote South Pacific location.' },
];
